# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Goto-Cached
version:      0.07
version_from: lib/Goto/Cached.pm
installdirs:  site
requires:
    Scope::Guard:                  0
    Test::More:                    0
    XSLoader:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
