--- #YAML:1.0
name:               Goto-Cached
version:            0.20
abstract:           a fast drop-in replacement for Perl's O(n) goto
author:
    - chocolateboy <chocolate@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    B::Hooks::OP::Annotation:  0.43
    B::Hooks::OP::Check:  0.18
    ExtUtils::Depends:    0.302
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    B::Hooks::EndOfScope:  0.09
    B::Hooks::OP::Annotation:  0.43
    B::Hooks::OP::Check:  0.18
    Devel::Pragma:        0.54
resources:
    repository:  http://github.com/chocolateboy/Goto-Cached
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
